language: python
matrix:
  include:
    - python: 2.7
      env:
      - TOXENV=py27
    - python: 3.4
      env:
      - TOXENV=py34
    - python: 3.5
      env:
      - TOXENV=py35
    - python: 3.6
      env:
      - TOXENV=py36
    - python: pypy
      env:
      - TOXENV=pypy
    - python: pypy3
      env:
      - TOXENV=pypy3
install:
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
deploy:
  provider: pypi
  user: pozole-rojo
  distributions: sdist bdist_wheel
  on:
    condition: $TOXENV == py27
    tags: true
    all_branches: true
    repo: pozole-rojo/advent-of-code-2018
